version: '3'

services:
  # Сервис для PostgreSQL
  work_scheduler_pg:
    image: postgres:16
    container_name: work_scheduler_pg
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - work_scheduler_data:/var/lib/postgresql/data

  alif_go_app:
    build: .
    container_name: alif_go_app
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - psql_alif


volumes:
  work_scheduler_data:
    driver: local
